version: '3.4'

services:
  weatherapi:
    image: weatherapi
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: ./docker-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - redis
    restart: on-failure
    volumes:
      - ./:/app
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redisdata:/data
volumes:
  pgdata:
  redisdata:  
